server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grade_journal_db
    username: postgres
    password: 346655
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVm"
    access-expiration-minutes: 30
    refresh-expiration-days: 30

logging:
  level:
    root: info
    com.example.grade_journal_back: debug