server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grade_journal_db
    username: postgres
    password: 346655
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    cache-names:
      - adminProfileOptions
      - groupViewerGroups
      - scheduleMeta
    redis:
      time-to-live: 10m
      cache-null-values: false
      use-key-prefix: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:Iv23li2yzcNdnIyZsQ2x}
            client-secret: ${GITHUB_CLIENT_SECRET:c431b2ef6754e39773a96cf2f3ebd623ea7c161d}
            scope:
              - read:user
              - user:email

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ${APP_JWT_SECRET:grade-journal-super-secret-key-2026-very-long-and-safe-123456789}
    access-expiration-minutes: 30
    refresh-expiration-days: 30
  oauth2:
    frontend-base-url: ${APP_OAUTH2_FRONTEND_BASE_URL:http://localhost:5173}

logging:
  level:
    root: info
    com.example.grade_journal_back: debug