#app.oauth2.frontend-base-url=${APP_OAUTH2_FRONTEND_BASE_URL:http://localhost:5173}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:PUT_GOOGLE_CLIENT_ID_HERE}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:PUT_GOOGLE_CLIENT_SECRET_HERE}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.oauth2.frontend-base-url=${APP_OAUTH2_FRONTEND_BASE_URL:http://localhost:5173}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Iv23li2yzcNdnIyZsQ2x}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:c431b2ef6754e39773a96cf2f3ebd623ea7c161d}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
