/* =====================================================================
   Электронный журнал успеваемости
   Полная финальная инициализация схемы + демо-данные + прогнозы
   PostgreSQL 12+
   Flyway V1
   ===================================================================== */

-- ---------------------------------------------------------------------
-- 1. Расширения
-- ---------------------------------------------------------------------
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- 2. Справочники и учетные записи
-- ---------------------------------------------------------------------
create table role (
    role_id      integer generated by default as identity primary key,
    role_code    varchar(20) not null unique,
    role_name    varchar(50) not null
);

create table user_account (
    user_account_id  integer generated by default as identity primary key,
    role_id          integer not null references role(role_id),
    username         varchar(50) not null unique,
    password_hash    varchar(100) not null,
    full_name        varchar(150) not null,
    email            varchar(150),
    is_active        boolean not null default true,
    is_approved      boolean not null default true,
    created_at       timestamptz not null default now()
);

create unique index uq_user_account_email_lower
    on user_account ((lower(email)))
    where email is not null;

create index idx_user_account_role on user_account(role_id);
create index idx_user_account_username_lower on user_account ((lower(username)));
create index idx_user_account_full_name_lower on user_account ((lower(full_name)));

create table refresh_token (
    refresh_token_id  integer generated by default as identity primary key,
    user_account_id   integer not null references user_account(user_account_id) on delete cascade,
    token_value       varchar(128) not null unique,
    expires_at        timestamptz not null,
    created_at        timestamptz not null default now(),
    revoked_at        timestamptz
);

create index idx_refresh_token_user on refresh_token(user_account_id);

create table registration_request (
    request_id        integer generated by default as identity primary key,
    desired_role      varchar(20) not null check (desired_role in ('teacher', 'student')),
    username          varchar(50) not null unique,
    password_hash     varchar(100) not null,
    full_name         varchar(150) not null,
    email             varchar(150),
    status            varchar(20) not null default 'pending'
                      check (status in ('pending', 'approved', 'rejected')),
    created_at        timestamptz not null default now(),
    approved_by       integer references user_account(user_account_id),
    approved_at       timestamptz
);

create index idx_registration_request_status on registration_request(status);

create table department (
    department_id     integer generated by default as identity primary key,
    department_code   varchar(20) not null unique,
    department_name   varchar(150) not null unique
);

create table study_group (
    group_id              integer generated by default as identity primary key,
    group_code            varchar(20) not null unique,
    course_no             smallint not null check (course_no between 1 and 6),
    admission_year        smallint not null,
    faculty_name          varchar(150) not null,
    specialization_name   varchar(150) not null
);

create index idx_study_group_course_no on study_group(course_no);

create table student (
    student_id         integer generated by default as identity primary key,
    user_account_id    integer not null unique references user_account(user_account_id) on delete cascade,
    group_id           integer not null references study_group(group_id),
    student_card       varchar(20) not null unique
);

create index idx_student_group on student(group_id);
create index idx_student_student_card on student(student_card);

create table teacher (
    teacher_id         integer generated by default as identity primary key,
    user_account_id    integer not null unique references user_account(user_account_id) on delete cascade,
    department_id      integer not null references department(department_id),
    position           varchar(100) not null,
    phone              varchar(30)
);

create index idx_teacher_department on teacher(department_id);

create table academic_term (
    term_id            integer generated by default as identity primary key,
    academic_year      varchar(20) not null,
    term_no            smallint not null check (term_no in (1, 2)),
    start_date         date not null,
    end_date           date not null,
    is_current         boolean not null default false,
    unique (academic_year, term_no),
    check (start_date < end_date)
);

create table course (
    course_id          integer generated by default as identity primary key,
    course_code        varchar(20) not null unique,
    course_name        varchar(150) not null,
    description        text,
    credits            smallint not null check (credits > 0),
    total_hours        integer not null check (total_hours > 0),
    study_year         smallint not null check (study_year between 1 and 6),
    control_form       varchar(20) not null
                       check (control_form in ('exam', 'test', 'credit'))
);

create index idx_course_study_year on course(study_year);

-- ---------------------------------------------------------------------
-- 3. Учебный процесс
-- ---------------------------------------------------------------------
create table course_offering (
    offering_id        integer generated by default as identity primary key,
    course_id          integer not null references course(course_id) on delete cascade,
    teacher_id         integer not null references teacher(teacher_id),
    group_id           integer not null references study_group(group_id) on delete cascade,
    term_id            integer not null references academic_term(term_id),
    status             varchar(20) not null default 'active'
                       check (status in ('planned', 'active', 'completed')),
    unique (course_id, teacher_id, group_id, term_id)
);

create index idx_course_offering_group_term on course_offering(group_id, term_id);
create index idx_course_offering_teacher on course_offering(teacher_id);
create index idx_course_offering_course on course_offering(course_id);

create table schedule_entry (
    schedule_id        integer generated by default as identity primary key,
    offering_id        integer not null references course_offering(offering_id) on delete cascade,
    lesson_date        date not null,
    time_slot          varchar(20) not null,
    lesson_type        varchar(20) not null
                       check (lesson_type in ('lecture', 'practice', 'lab', 'seminar', 'exam', 'consultation')),
    room               varchar(20),
    topic              varchar(200),
    unique (offering_id, lesson_date, time_slot)
);

create index idx_schedule_entry_offering_date on schedule_entry(offering_id, lesson_date);

create table enrollment (
    enrollment_id      integer generated by default as identity primary key,
    student_id         integer not null references student(student_id) on delete cascade,
    offering_id        integer not null references course_offering(offering_id) on delete cascade,
    enrollment_date    date not null default current_date,
    missed_hours       integer not null default 0 check (missed_hours >= 0),
    current_status     varchar(20) not null default 'active'
                       check (current_status in ('active', 'completed', 'dropped')),
    unique (student_id, offering_id)
);

create index idx_enrollment_student on enrollment(student_id);
create index idx_enrollment_offering on enrollment(offering_id);

create table assessment_type (
    assessment_type_id integer generated by default as identity primary key,
    type_code          varchar(20) not null unique,
    type_name          varchar(100) not null,
    default_weight     numeric(5,2) not null check (default_weight >= 0 and default_weight <= 1),
    allows_multiple    boolean not null default true
);

create table assessment_item (
    assessment_item_id   integer generated by default as identity primary key,
    offering_id          integer not null references course_offering(offering_id) on delete cascade,
    assessment_type_id   integer not null references assessment_type(assessment_type_id),
    title                varchar(200) not null,
    max_score            numeric(5,2) not null default 10.00 check (max_score > 0),
    weight               numeric(5,2) not null check (weight >= 0 and weight <= 1),
    due_date             date not null,
    schedule_id          integer references schedule_entry(schedule_id) on delete set null,
    is_required          boolean not null default true
);

create index idx_assessment_item_offering on assessment_item(offering_id);
create index idx_assessment_item_schedule on assessment_item(schedule_id);

create table attendance (
    attendance_id      integer generated by default as identity primary key,
    enrollment_id      integer not null references enrollment(enrollment_id) on delete cascade,
    schedule_id        integer not null references schedule_entry(schedule_id) on delete cascade,
    is_present         boolean not null,
    note               text,
    unique (enrollment_id, schedule_id)
);

create index idx_attendance_enrollment on attendance(enrollment_id);
create index idx_attendance_schedule on attendance(schedule_id);

create table grade (
    grade_id           integer generated by default as identity primary key,
    enrollment_id      integer not null references enrollment(enrollment_id) on delete cascade,
    assessment_item_id integer not null references assessment_item(assessment_item_id) on delete cascade,
    grade_value        numeric(4,2) not null check (grade_value >= 0 and grade_value <= 10),
    teacher_comment    text,
    graded_at          timestamptz not null default now(),
    unique (enrollment_id, assessment_item_id)
);

create index idx_grade_enrollment on grade(enrollment_id);
create index idx_grade_assessment_item on grade(assessment_item_id);

-- ---------------------------------------------------------------------
-- 4. Прогнозирование и рекомендации
-- ---------------------------------------------------------------------
create table performance_prediction (
    prediction_id            integer generated by default as identity primary key,
    enrollment_id            integer not null references enrollment(enrollment_id) on delete cascade,
    current_average          numeric(4,2) not null check (current_average >= 0 and current_average <= 10),
    attendance_rate          numeric(5,2) not null check (attendance_rate >= 0 and attendance_rate <= 100),
    missed_hours             integer not null check (missed_hours >= 0),
    predicted_final_grade    numeric(4,2) not null check (predicted_final_grade >= 0 and predicted_final_grade <= 10),
    risk_level               varchar(20) not null check (risk_level in ('low', 'medium', 'high')),
    confidence_score         numeric(5,2) not null check (confidence_score >= 0 and confidence_score <= 1),
    missing_required_count   integer not null default 0 check (missing_required_count >= 0),
    recommendation_summary   text,
    model_version            varchar(50) not null,
    generated_at             timestamptz not null default now()
);

create index idx_prediction_enrollment on performance_prediction(enrollment_id);

create table student_recommendation (
    recommendation_id     integer generated by default as identity primary key,
    enrollment_id         integer not null references enrollment(enrollment_id) on delete cascade,
    prediction_id         integer references performance_prediction(prediction_id) on delete cascade,
    recommendation_type   varchar(30) not null
                          check (recommendation_type in ('attendance', 'performance', 'assignment', 'support')),
    recommendation_text   text not null,
    priority              smallint not null check (priority between 1 and 5),
    status                varchar(20) not null default 'new'
                          check (status in ('new', 'in_progress', 'done', 'dismissed')),
    created_at            timestamptz not null default now()
);

create index idx_recommendation_prediction on student_recommendation(prediction_id);
create index idx_recommendation_enrollment on student_recommendation(enrollment_id);

-- ---------------------------------------------------------------------
-- 5. Триггеры для учета пропущенных часов
-- ---------------------------------------------------------------------
create or replace function fn_update_missed_hours_after_insert()
returns trigger
language plpgsql
as $$
begin
    if new.is_present = false then
        update enrollment
        set missed_hours = missed_hours + 2
        where enrollment_id = new.enrollment_id;
    end if;
    return new;
end;
$$;

create trigger trg_attendance_after_insert
after insert on attendance
for each row
execute function fn_update_missed_hours_after_insert();

create or replace function fn_update_missed_hours_after_update()
returns trigger
language plpgsql
as $$
begin
    if old.is_present = true and new.is_present = false then
        update enrollment
        set missed_hours = missed_hours + 2
        where enrollment_id = new.enrollment_id;
    elsif old.is_present = false and new.is_present = true then
        update enrollment
        set missed_hours = greatest(missed_hours - 2, 0)
        where enrollment_id = new.enrollment_id;
    end if;

    return new;
end;
$$;

create trigger trg_attendance_after_update
after update on attendance
for each row
execute function fn_update_missed_hours_after_update();

create or replace function fn_update_missed_hours_after_delete()
returns trigger
language plpgsql
as $$
begin
    if old.is_present = false then
        update enrollment
        set missed_hours = greatest(missed_hours - 2, 0)
        where enrollment_id = old.enrollment_id;
    end if;

    return old;
end;
$$;

create trigger trg_attendance_after_delete
after delete on attendance
for each row
execute function fn_update_missed_hours_after_delete();

-- ---------------------------------------------------------------------
-- 6. Базовые справочники
-- ---------------------------------------------------------------------
insert into role (role_code, role_name)
values
    ('admin', 'Администратор'),
    ('teacher', 'Преподаватель'),
    ('student', 'Студент');

insert into department (department_code, department_name)
values
    ('EI', 'Кафедра экономической информатики'),
    ('PI', 'Кафедра программной инженерии'),
    ('MM', 'Кафедра математических методов'),
    ('IS', 'Кафедра информационных систем');

insert into academic_term (academic_year, term_no, start_date, end_date, is_current)
values
    ('2024/2025', 2, date '2025-02-03', date '2025-06-30', false),
    ('2025/2026', 1, date '2025-09-01', date '2026-01-25', false),
    ('2025/2026', 2, date '2026-02-02', date '2026-06-30', true);

insert into study_group (group_code, course_no, admission_year, faculty_name, specialization_name)
values
    ('251001', 1, 2025, 'Инженерно-экономический факультет', 'Экономическая информатика'),
    ('251002', 1, 2025, 'Инженерно-экономический факультет', 'Экономическая информатика'),
    ('251003', 1, 2025, 'Инженерно-экономический факультет', 'Экономическая информатика'),
    ('241001', 2, 2024, 'Инженерно-экономический факультет', 'Экономическая информатика'),
    ('241002', 2, 2024, 'Инженерно-экономический факультет', 'Экономическая информатика'),
    ('241003', 2, 2024, 'Инженерно-экономический факультет', 'Экономическая информатика'),
    ('231001', 3, 2023, 'Инженерно-экономический факультет', 'Экономическая информатика'),
    ('231002', 3, 2023, 'Инженерно-экономический факультет', 'Экономическая информатика'),
    ('221001', 4, 2022, 'Инженерно-экономический факультет', 'Экономическая информатика'),
    ('221002', 4, 2022, 'Инженерно-экономический факультет', 'Экономическая информатика');

insert into course (course_code, course_name, description, credits, total_hours, study_year, control_form)
values
    ('MATH101', 'Высшая математика', 'Базовый математический курс для студентов 1 курса', 5, 144, 1, 'exam'),
    ('PROG101', 'Основы программирования', 'Введение в программирование и алгоритмическое мышление', 5, 144, 1, 'exam'),
    ('DM101', 'Дискретная математика', 'Основы дискретных структур и логики', 4, 108, 1, 'test'),
    ('ECON101', 'Цифровая экономика', 'Введение в цифровую трансформацию экономики', 4, 108, 1, 'credit'),

    ('OOP201', 'Объектно-ориентированное программирование', 'Классы, наследование, полиморфизм, паттерны', 5, 144, 2, 'exam'),
    ('DB201', 'Базы данных', 'Проектирование БД, SQL, нормализация, транзакции', 5, 144, 2, 'exam'),
    ('STAT201', 'Теория вероятностей и статистика', 'Статистические методы и вероятностные модели', 4, 108, 2, 'test'),
    ('WEB201', 'Web-программирование', 'Клиент-серверные web-приложения', 4, 108, 2, 'credit'),

    ('SE301', 'Инженерия программного обеспечения', 'Проектирование и сопровождение ПО', 5, 144, 3, 'exam'),
    ('DS301', 'Анализ данных', 'Подготовка данных, визуализация, интерпретация', 5, 144, 3, 'exam'),
    ('ML301', 'Введение в машинное обучение', 'Базовые модели машинного обучения', 4, 108, 3, 'test'),
    ('IS301', 'Информационные системы', 'Архитектура и разработка информационных систем', 4, 108, 3, 'credit'),

    ('BIG401', 'Большие данные', 'Хранение и обработка больших объемов данных', 5, 144, 4, 'exam'),
    ('BI401', 'Бизнес-аналитика', 'Методы принятия решений и аналитические панели', 4, 108, 4, 'test'),
    ('PRED401', 'Прогнозирование', 'Методы прогнозирования и оценка точности моделей', 5, 144, 4, 'exam'),
    ('DSS401', 'Системы поддержки принятия решений', 'Модели и методы поддержки решений', 4, 108, 4, 'credit');

insert into assessment_type (type_code, type_name, default_weight, allows_multiple)
values
    ('lab',  'Лабораторная работа', 0.20, true),
    ('quiz', 'Краткий тест',        0.10, true),
    ('test', 'Контрольная работа',  0.25, true),
    ('exam', 'Экзамен',             0.30, false);

-- ---------------------------------------------------------------------
-- 7. Пользователи
-- ---------------------------------------------------------------------
insert into user_account (role_id, username, password_hash, full_name, email)
values
(
    (select role_id from role where role_code = 'admin'),
    'admin',
    crypt('admin', gen_salt('bf')),
    'Системный администратор',
    'admin@ejournal.by'
);

insert into user_account (role_id, username, password_hash, full_name, email)
select
    (select role_id from role where role_code = 'teacher'),
    'teacher' || lpad(i::text, 2, '0'),
    crypt('teach' || lpad(i::text, 2, '0'), gen_salt('bf')),
    'Преподаватель ' || i,
    'teacher' || lpad(i::text, 2, '0') || '@ejournal.by'
from generate_series(1, 15) as g(i);

insert into user_account (role_id, username, password_hash, full_name, email)
select
    (select role_id from role where role_code = 'student'),
    'student' || lpad(i::text, 3, '0'),
    crypt('stud' || lpad(i::text, 3, '0'), gen_salt('bf')),
    'Студент ' || i,
    'student' || lpad(i::text, 3, '0') || '@ejournal.by'
from generate_series(1, 120) as g(i);

-- ---------------------------------------------------------------------
-- 8. Преподаватели и студенты
-- ---------------------------------------------------------------------
insert into teacher (user_account_id, department_id, position, phone)
select
    ua.user_account_id,
    ((row_number() over (order by ua.user_account_id) - 1) % 4) + 1 as department_id,
    case
        when row_number() over (order by ua.user_account_id) <= 5 then 'Профессор'
        when row_number() over (order by ua.user_account_id) <= 10 then 'Доцент'
        else 'Старший преподаватель'
    end as position,
    '+37529' || lpad((1000000 + row_number() over (order by ua.user_account_id))::text, 7, '0')
from user_account ua
join role r on r.role_id = ua.role_id
where r.role_code = 'teacher'
order by ua.user_account_id;

with student_users as (
    select
        ua.user_account_id,
        row_number() over (order by ua.user_account_id) as rn
    from user_account ua
    join role r on r.role_id = ua.role_id
    where r.role_code = 'student'
),
student_groups as (
    select
        su.user_account_id,
        ((su.rn - 1) / 12) + 1 as group_id,
        row_number() over (
            partition by ((su.rn - 1) / 12) + 1
            order by su.user_account_id
        ) as idx_in_group
    from student_users su
)
insert into student (user_account_id, group_id, student_card)
select
    sg.user_account_id,
    sg.group_id,
    gr.group_code || lpad(sg.idx_in_group::text, 2, '0')
from student_groups sg
join study_group gr on gr.group_id = sg.group_id
order by sg.user_account_id;

-- ---------------------------------------------------------------------
-- 9. Токены и заявки на регистрацию
-- ---------------------------------------------------------------------
insert into refresh_token (user_account_id, token_value, expires_at)
select
    user_account_id,
    encode(gen_random_bytes(32), 'hex'),
    now() + interval '30 days'
from user_account
order by user_account_id
limit 10;

insert into registration_request (desired_role, username, password_hash, full_name, email, status)
values
    ('student', 'applicant001', crypt('demo001', gen_salt('bf')), 'Демо Студент', 'applicant001@ejournal.by', 'pending'),
    ('teacher', 'candidate001', crypt('demo002', gen_salt('bf')), 'Демо Преподаватель', 'candidate001@ejournal.by', 'pending'),
    ('student', 'applicant002', crypt('demo003', gen_salt('bf')), 'Отклоненный Пользователь', 'applicant002@ejournal.by', 'rejected');

-- ---------------------------------------------------------------------
-- 10. Учебные назначения дисциплин группам
-- ---------------------------------------------------------------------
with current_term as (
    select term_id
    from academic_term
    where is_current = true
),
curriculum as (
    select
        sg.group_id,
        c.course_id,
        row_number() over (partition by sg.group_id order by c.course_id) as course_rank
    from study_group sg
    join course c on c.study_year = sg.course_no
)
insert into course_offering (course_id, teacher_id, group_id, term_id, status)
select
    cur.course_id,
    ((cur.group_id + cur.course_rank - 2) % 15) + 1 as teacher_id,
    cur.group_id,
    ct.term_id,
    'active'
from curriculum cur
cross join current_term ct
order by cur.group_id, cur.course_id;

-- ---------------------------------------------------------------------
-- 11. Расписание
-- 4 дисциплины на группу, по 12 занятий на каждую
-- Чтобы уже сейчас было достаточно прошедших занятий для 3-8 оценок
-- ---------------------------------------------------------------------
with current_term as (
    select
        term_id,
        greatest(start_date, current_date - 36) as base_date
    from academic_term
    where is_current = true
),
offering_rank as (
    select
        co.offering_id,
        co.group_id,
        c.course_name,
        row_number() over (partition by co.group_id order by c.course_id) as course_rank
    from course_offering co
    join course c on c.course_id = co.course_id
    join current_term ct on ct.term_id = co.term_id
)
insert into schedule_entry (offering_id, lesson_date, time_slot, lesson_type, room, topic)
select
    orr.offering_id,
    ct.base_date + (((orr.course_rank - 1)::int) + ((gs.lesson_idx)::int * 3)) as lesson_date,
    case orr.course_rank
        when 1 then '09:00-10:20'
        when 2 then '10:35-11:55'
        when 3 then '12:25-13:45'
        else        '14:00-15:20'
    end as time_slot,
    case
        when gs.lesson_idx in (0, 3, 6, 9) then 'lecture'
        when gs.lesson_idx in (1, 4, 7, 10) then 'practice'
        else 'lab'
    end as lesson_type,
    'А-' || lpad((100 + ((orr.group_id + orr.course_rank::int + gs.lesson_idx::int) % 20))::text, 3, '0') as room,
    'Занятие ' || (gs.lesson_idx + 1) || ': ' || orr.course_name as topic
from offering_rank orr
cross join current_term ct
cross join generate_series(0, 11) as gs(lesson_idx)
order by orr.offering_id, lesson_date;

-- ---------------------------------------------------------------------
-- 12. Зачисление студентов на дисциплины своей группы
-- ---------------------------------------------------------------------
insert into enrollment (student_id, offering_id, enrollment_date, current_status)
select
    s.student_id,
    co.offering_id,
    current_date,
    'active'
from student s
join course_offering co on co.group_id = s.group_id
order by s.student_id, co.offering_id;

-- ---------------------------------------------------------------------
-- 13. Контрольные точки
-- По каждой дисциплине создаем 8 оценочных точек.
-- Первые 4 обязательные, остальные дополнительные.
-- ---------------------------------------------------------------------
with ranked_schedule as (
    select
        se.schedule_id,
        se.offering_id,
        se.lesson_date,
        row_number() over (
            partition by se.offering_id
            order by se.lesson_date, se.time_slot
        ) as lesson_no
    from schedule_entry se
),
first_eight as (
    select *
    from ranked_schedule
    where lesson_no <= 8
)
insert into assessment_item (
    offering_id,
    assessment_type_id,
    title,
    max_score,
    weight,
    due_date,
    schedule_id,
    is_required
)
select
    fe.offering_id,
    case fe.lesson_no
        when 1 then (select assessment_type_id from assessment_type where type_code = 'quiz')
        when 2 then (select assessment_type_id from assessment_type where type_code = 'lab')
        when 3 then (select assessment_type_id from assessment_type where type_code = 'quiz')
        when 4 then (select assessment_type_id from assessment_type where type_code = 'test')
        when 5 then (select assessment_type_id from assessment_type where type_code = 'lab')
        when 6 then (select assessment_type_id from assessment_type where type_code = 'quiz')
        when 7 then (select assessment_type_id from assessment_type where type_code = 'lab')
        when 8 then (select assessment_type_id from assessment_type where type_code = 'exam')
    end as assessment_type_id,
    case fe.lesson_no
        when 1 then 'Краткий тест 1'
        when 2 then 'Лабораторная работа 1'
        when 3 then 'Краткий тест 2'
        when 4 then 'Контрольная работа'
        when 5 then 'Лабораторная работа 2'
        when 6 then 'Краткий тест 3'
        when 7 then 'Лабораторная работа 3'
        when 8 then 'Итоговая работа'
    end as title,
    10.00,
    case fe.lesson_no
        when 1 then 0.08
        when 2 then 0.12
        when 3 then 0.08
        when 4 then 0.18
        when 5 then 0.12
        when 6 then 0.08
        when 7 then 0.14
        when 8 then 0.20
    end as weight,
    fe.lesson_date,
    fe.schedule_id,
    case
        when fe.lesson_no <= 4 then true
        else false
    end as is_required
from first_eight fe
order by fe.offering_id, fe.lesson_no;

-- ---------------------------------------------------------------------
-- 14. Посещаемость
-- Делаем живой разброс посещаемости по всем прошедшим занятиям
-- При этом у каждого студента по предмету будет от 3 до 8 оценок
-- ---------------------------------------------------------------------
with ranked_schedule as (
    select
        se.schedule_id,
        se.offering_id,
        se.lesson_date,
        row_number() over (
            partition by se.offering_id
            order by se.lesson_date, se.time_slot
        ) as lesson_no
    from schedule_entry se
    where se.lesson_date < current_date
),
targets as (
    select
        e.enrollment_id,
        e.student_id,
        co.course_id,
        e.offering_id,
        3 + ((e.student_id + co.course_id) % 6) as target_grade_count
    from enrollment e
    join course_offering co on co.offering_id = e.offering_id
)
insert into attendance (enrollment_id, schedule_id, is_present, note)
select
    t.enrollment_id,
    rs.schedule_id,
    case
        when rs.lesson_no <= t.target_grade_count then true
        when rs.lesson_no <= 8 and ((t.student_id + t.course_id + rs.lesson_no) % 3) = 0 then false
        when rs.lesson_no > 8 and ((t.student_id + t.course_id + rs.lesson_no) % 7) = 0 then false
        else true
    end as is_present,
    case
        when rs.lesson_no <= 8 and rs.lesson_no > t.target_grade_count and ((t.student_id + t.course_id + rs.lesson_no) % 3) = 0
            then 'Пропуск контрольного занятия'
        when rs.lesson_no > 8 and ((t.student_id + t.course_id + rs.lesson_no) % 7) = 0
            then 'Пропуск обычного занятия'
        else null
    end as note
from targets t
join ranked_schedule rs on rs.offering_id = t.offering_id
on conflict (enrollment_id, schedule_id) do nothing;

-- ---------------------------------------------------------------------
-- 15. Оценки
-- У каждого студента по каждому предмету будет от 3 до 8 оценок
-- ---------------------------------------------------------------------
with ranked_items as (
    select
        ai.assessment_item_id,
        ai.offering_id,
        ai.schedule_id,
        ai.due_date,
        row_number() over (
            partition by ai.offering_id
            order by ai.due_date, ai.assessment_item_id
        ) as point_no
    from assessment_item ai
),
targets as (
    select
        e.enrollment_id,
        e.student_id,
        co.course_id,
        e.offering_id,
        3 + ((e.student_id + co.course_id) % 6) as target_grade_count
    from enrollment e
    join course_offering co on co.offering_id = e.offering_id
)
insert into grade (
    enrollment_id,
    assessment_item_id,
    grade_value,
    teacher_comment,
    graded_at
)
select
    t.enrollment_id,
    ri.assessment_item_id,
    round(
        greatest(
            3::numeric,
            least(
                10::numeric,
                (
                    4
                    + ((t.student_id + t.course_id + ri.point_no) % 4)
                    + case
                        when t.target_grade_count >= 6 then 1
                        else 0
                      end
                    + case
                        when ((t.student_id + t.course_id) % 3) = 0
                             and ri.point_no >= greatest(t.target_grade_count - 1, 1) then 1
                        else 0
                      end
                    - case
                        when ((t.student_id + t.course_id) % 4) = 0
                             and ri.point_no = t.target_grade_count then 1
                        else 0
                      end
                )::numeric
            )
        ),
        0
    ) as grade_value,
    case
        when ((t.student_id + t.course_id) % 3) = 0 and ri.point_no = t.target_grade_count
            then 'Есть положительная динамика по последним работам'
        when ((t.student_id + t.course_id) % 4) = 0 and ri.point_no = t.target_grade_count
            then 'Последняя работа слабее предыдущих'
        when t.target_grade_count <= 4 and ri.point_no = t.target_grade_count
            then 'Нужно усилить подготовку по следующим занятиям'
        else '—'
    end as teacher_comment,
    (ri.due_date::timestamp + interval '18 hour')::timestamptz
from targets t
join ranked_items ri
    on ri.offering_id = t.offering_id
   and ri.point_no <= t.target_grade_count
join attendance att
    on att.enrollment_id = t.enrollment_id
   and att.schedule_id = ri.schedule_id
   and att.is_present = true
order by t.enrollment_id, ri.point_no
on conflict (enrollment_id, assessment_item_id) do nothing;

-- ---------------------------------------------------------------------
-- 16. Все оценки делаем целыми
-- ---------------------------------------------------------------------
update grade
set grade_value = round(grade_value, 0);

-- ---------------------------------------------------------------------
-- 17. Пересчитываем пропущенные часы с нуля
-- ---------------------------------------------------------------------
with missed as (
    select
        e.enrollment_id,
        coalesce(count(*) filter (where a.is_present = false) * 2, 0) as missed_hours_value
    from enrollment e
    left join attendance a on a.enrollment_id = e.enrollment_id
    group by e.enrollment_id
)
update enrollment e
set missed_hours = m.missed_hours_value
from missed m
where e.enrollment_id = m.enrollment_id;

-- ---------------------------------------------------------------------
-- 18. Прогноз итоговых результатов
-- Более детальная и живая логика
-- ---------------------------------------------------------------------
with grade_stats as (
    select
        e.enrollment_id,
        coalesce(round(avg(g.grade_value)::numeric, 2), 0.00) as avg_grade,
        count(g.grade_id) as graded_items
    from enrollment e
    left join grade g on g.enrollment_id = e.enrollment_id
    group by e.enrollment_id
),
attendance_stats as (
    select
        e.enrollment_id,
        count(a.attendance_id) as total_lessons,
        count(a.attendance_id) filter (where a.is_present) as present_lessons
    from enrollment e
    left join attendance a on a.enrollment_id = e.enrollment_id
    group by e.enrollment_id
),
required_stats as (
    select
        e.enrollment_id,
        count(ai.assessment_item_id) filter (
            where ai.is_required = true
              and ai.due_date < current_date
        ) as expected_items,
        count(g.grade_id) filter (
            where ai.is_required = true
              and ai.due_date < current_date
        ) as completed_items
    from enrollment e
    left join assessment_item ai
        on ai.offering_id = e.offering_id
    left join grade g
        on g.enrollment_id = e.enrollment_id
       and g.assessment_item_id = ai.assessment_item_id
    group by e.enrollment_id
),
recent_grades as (
    select
        x.enrollment_id,
        string_agg(x.grade_value::text, ', ' order by x.graded_at desc, x.grade_id desc) as last_three_grades
    from (
        select
            g.enrollment_id,
            g.grade_id,
            g.grade_value,
            g.graded_at,
            row_number() over (
                partition by g.enrollment_id
                order by g.graded_at desc, g.grade_id desc
            ) as rn
        from grade g
    ) x
    where x.rn <= 3
    group by x.enrollment_id
),
trend_stats as (
    select
        z.enrollment_id,
        max(case when z.rn_asc = 1 then z.grade_value end) as first_grade,
        max(case when z.rn_desc = 1 then z.grade_value end) as last_grade,
        count(*) as grade_count
    from (
        select
            g.enrollment_id,
            g.grade_value,
            row_number() over (
                partition by g.enrollment_id
                order by g.graded_at asc, g.grade_id asc
            ) as rn_asc,
            row_number() over (
                partition by g.enrollment_id
                order by g.graded_at desc, g.grade_id desc
            ) as rn_desc
        from grade g
    ) z
    group by z.enrollment_id
),
base as (
    select
        e.enrollment_id,
        co.course_id,
        c.course_name,
        coalesce(gs.avg_grade, 0.00) as current_average,
        coalesce(gs.graded_items, 0) as graded_items,
        round(
            case
                when coalesce(ast.total_lessons, 0) = 0 then 100.00
                else ast.present_lessons::numeric * 100.00 / ast.total_lessons
            end,
            2
        ) as attendance_rate,
        e.missed_hours,
        greatest(coalesce(rs.expected_items, 0) - coalesce(rs.completed_items, 0), 0) as missing_required_count,
        coalesce(rg.last_three_grades, 'нет данных') as last_three_grades,
        case
            when coalesce(ts.grade_count, 0) = 0 then 'нет данных'
            when coalesce(ts.grade_count, 0) = 1 then 'недостаточно данных'
            when ts.last_grade >= ts.first_grade + 1 then 'рост'
            when ts.last_grade <= ts.first_grade - 1 then 'снижение'
            else 'стабильность'
        end as trend,
        round(
            least(
                10.00::numeric,
                greatest(
                    1.00::numeric,
                    (
                        (case when coalesce(gs.avg_grade, 0) = 0 then 6.00 else gs.avg_grade end) * 0.82
                        + (
                            case
                                when coalesce(ast.total_lessons, 0) = 0 then 1.00
                                else ast.present_lessons::numeric / ast.total_lessons
                            end
                          ) * 1.80
                        - greatest(coalesce(rs.expected_items, 0) - coalesce(rs.completed_items, 0), 0) * 0.40
                        - e.missed_hours * 0.03
                        + case
                            when coalesce(ts.grade_count, 0) >= 2 and ts.last_grade >= ts.first_grade + 1 then 0.40
                            when coalesce(ts.grade_count, 0) >= 2 and ts.last_grade <= ts.first_grade - 1 then -0.40
                            else 0.00
                          end
                    )::numeric
                )
            ),
            0
        ) as predicted_final_grade,
        round(
            least(
                0.95::numeric,
                (
                    0.55
                    + least(coalesce(ast.total_lessons, 0), 12) * 0.015
                    + least(coalesce(gs.graded_items, 0), 8) * 0.03
                )::numeric
            ),
            2
        ) as confidence_score
    from enrollment e
    join course_offering co on co.offering_id = e.offering_id
    join course c on c.course_id = co.course_id
    left join grade_stats gs on gs.enrollment_id = e.enrollment_id
    left join attendance_stats ast on ast.enrollment_id = e.enrollment_id
    left join required_stats rs on rs.enrollment_id = e.enrollment_id
    left join recent_grades rg on rg.enrollment_id = e.enrollment_id
    left join trend_stats ts on ts.enrollment_id = e.enrollment_id
)
insert into performance_prediction (
    enrollment_id,
    current_average,
    attendance_rate,
    missed_hours,
    predicted_final_grade,
    risk_level,
    confidence_score,
    missing_required_count,
    recommendation_summary,
    model_version,
    generated_at
)
select
    b.enrollment_id,
    b.current_average,
    b.attendance_rate,
    b.missed_hours,
    b.predicted_final_grade,
    case
        when b.graded_items = 0
          or b.current_average < 6.00
          or b.attendance_rate < 70.00
          or b.missing_required_count >= 2 then 'high'
        when b.current_average < 7.50
          or b.attendance_rate < 85.00
          or b.missing_required_count = 1 then 'medium'
        else 'low'
    end as risk_level,
    b.confidence_score,
    b.missing_required_count,
    case
        when b.graded_items = 0 then
            'По дисциплине "' || b.course_name || '" пока нет ни одной оценки. Посещаемость: ' || b.attendance_rate
            || '%, пропущено часов: ' || b.missed_hours || '. Нужно начать с выполнения ближайшей контрольной точки.'
        else
            'По дисциплине "' || b.course_name || '" средний балл ' || b.current_average
            || ', посещаемость ' || b.attendance_rate || '%, пропущено часов: ' || b.missed_hours
            || '. Последние оценки: ' || b.last_three_grades
            || '. Текущая динамика: ' || b.trend
            || '. Прогнозная следующая оценка: ' || b.predicted_final_grade || '.'
    end as recommendation_summary,
    'init-v2-live',
    now()
from base b
order by b.enrollment_id;

-- ---------------------------------------------------------------------
-- 19. Рекомендации студентам
-- Конкретные рекомендации со значениями
-- ---------------------------------------------------------------------

-- 19.1. Нет оценок
insert into student_recommendation (
    enrollment_id,
    prediction_id,
    recommendation_type,
    recommendation_text,
    priority,
    status
)
select
    pp.enrollment_id,
    pp.prediction_id,
    'assignment',
    'По предмету "' || c.course_name || '" пока нет оценок. Необходимо закрыть первую доступную контрольную точку, чтобы система могла строить более точный прогноз.',
    5,
    'new'
from performance_prediction pp
join enrollment e on e.enrollment_id = pp.enrollment_id
join course_offering co on co.offering_id = e.offering_id
join course c on c.course_id = co.course_id
where pp.current_average = 0;

-- 19.2. Низкая посещаемость
insert into student_recommendation (
    enrollment_id,
    prediction_id,
    recommendation_type,
    recommendation_text,
    priority,
    status
)
select
    pp.enrollment_id,
    pp.prediction_id,
    'attendance',
    'По предмету "' || c.course_name || '" посещаемость составляет ' || pp.attendance_rate
    || '%. Для улучшения результата рекомендуется сократить пропуски и стабилизировать присутствие хотя бы на ближайших 2-3 занятиях подряд.',
    case
        when pp.attendance_rate < 70 then 5
        else 4
    end,
    'new'
from performance_prediction pp
join enrollment e on e.enrollment_id = pp.enrollment_id
join course_offering co on co.offering_id = e.offering_id
join course c on c.course_id = co.course_id
where pp.attendance_rate < 85;

-- 19.3. Низкий или средний балл
insert into student_recommendation (
    enrollment_id,
    prediction_id,
    recommendation_type,
    recommendation_text,
    priority,
    status
)
select
    pp.enrollment_id,
    pp.prediction_id,
    'performance',
    'По предмету "' || c.course_name || '" текущий средний балл составляет ' || pp.current_average
    || '. Для выхода на более уверенный уровень желательно получить по следующим работам оценки не ниже '
    || least(10, greatest(7, pp.predicted_final_grade + 1)) || '.',
    case
        when pp.current_average < 6 then 5
        else 4
    end,
    'new'
from performance_prediction pp
join enrollment e on e.enrollment_id = pp.enrollment_id
join course_offering co on co.offering_id = e.offering_id
join course c on c.course_id = co.course_id
where pp.current_average > 0
  and pp.current_average < 7.5;

-- 19.4. Есть незакрытые обязательные точки
insert into student_recommendation (
    enrollment_id,
    prediction_id,
    recommendation_type,
    recommendation_text,
    priority,
    status
)
select
    pp.enrollment_id,
    pp.prediction_id,
    'assignment',
    'По предмету "' || c.course_name || '" не закрыто обязательных контрольных точек: ' || pp.missing_required_count
    || '. Их рекомендуется закрыть в первую очередь, иначе итоговый прогноз останется заниженным.',
    5,
    'new'
from performance_prediction pp
join enrollment e on e.enrollment_id = pp.enrollment_id
join course_offering co on co.offering_id = e.offering_id
join course c on c.course_id = co.course_id
where pp.missing_required_count > 0;

-- 19.5. Поддерживающая рекомендация для сильных студентов
insert into student_recommendation (
    enrollment_id,
    prediction_id,
    recommendation_type,
    recommendation_text,
    priority,
    status
)
select
    pp.enrollment_id,
    pp.prediction_id,
    'support',
    'По предмету "' || c.course_name || '" результат хороший: средний балл ' || pp.current_average
    || ', посещаемость ' || pp.attendance_rate || '%. Дополнительные рекомендации не требуются — достаточно сохранять текущий темп.',
    1,
    'new'
from performance_prediction pp
join enrollment e on e.enrollment_id = pp.enrollment_id
join course_offering co on co.offering_id = e.offering_id
join course c on c.course_id = co.course_id
where pp.risk_level = 'low'
  and not exists (
      select 1
      from student_recommendation sr
      where sr.prediction_id = pp.prediction_id
  );